### ISSUE TITLE
what tags mean in grafana.snapshots.create_snapshot?

### ISSUE THREAD

**Issue by yangminglintw** [ohmrefresh/grafana-snapshot#11]
I use grafana.snapshots.create_snapshot to create snapshot but the retrun is empty list. Could you help me what argument should I put in tags? 
Thank you.

**Comment by Panchorn** [comment]
This library will find the dashboard by tags name.
So you have to set `Tags` on Grafana dashboard first. 
Go to your dashboard > Settings > General > Tags, then put tag name here.

![image](https://user-images.githubusercontent.com/17079307/69781520-09ec0d00-11e1-11ea-93ea-a06f5505b626.png)

**Comment by yangminglintw** [comment]
It work! Thank you for helping. 
It is a convenient tool to generate the snapshot.
